# Generated by Django 3.2 on 2021-12-20 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('matricule', models.TextField(blank=True, null=True)),
                ('service', models.TextField(blank=True, null=True)),
                ('fonction', models.TextField(blank=True, null=True)),
                ('date_debut_fonction', models.DateField(blank=True, null=True)),
                ('date_fin_fonction', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_responsable', models.BooleanField(default=False)),
                ('is_developper', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('codification', models.CharField(max_length=255)),
                ('nature', models.CharField(max_length=20)),
                ('statut', models.TextField(default='en_cours', max_length=20)),
                ('nbr_jours', models.IntegerField()),
                ('developpeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('email_source', models.EmailField(max_length=254)),
                ('email_destination', models.EmailField(max_length=254)),
                ('absence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmsapp.absence')),
            ],
        ),
    ]
