# Generated by Django 3.2 on 2021-12-20 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mail',
        ),
    ]
