# Generated by Django 3.2 on 2021-12-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='est_valide',
            field=models.BooleanField(default=False),
        ),
    ]
