# Generated by Django 3.2 on 2021-12-16 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0002_auto_20211216_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='developpeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='date_debut_fonction',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='date_fin_fonction',
            field=models.DateField(blank=True, null=True),
        ),
    ]
