# Generated by Django 3.2 on 2021-12-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0003_auto_20211216_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateur',
            name='fonction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='matricule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='service',
            field=models.TextField(blank=True, null=True),
        ),
    ]
