# Generated by Django 3.2 on 2021-12-16 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0005_rename_id_admin_collaborateur_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateur',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
