# Generated by Django 3.2 on 2021-12-20 08:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0006_collaborateur_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='absence',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hrmsapp.absence'),
            preserve_default=False,
        ),
    ]
