# Generated by Django 3.2 on 2021-12-20 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0008_auto_20211220_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='cause',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='est_valide',
        ),
        migrations.AddField(
            model_name='absence',
            name='statut',
            field=models.TextField(default='en_cours', max_length=20),
        ),
        migrations.AlterField(
            model_name='absence',
            name='developpeur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hrmsapp.collaborateur'),
        ),
    ]
