# Generated by Django 3.2 on 2021-12-20 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0009_auto_20211220_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='developpeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
